package com.yhkj.yymall.bean.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yhkj.yymall.bean.RecnetSearchBean;
import com.yhkj.yymall.bean.UserConfig;

import com.yhkj.yymall.bean.db.RecnetSearchBeanDao;
import com.yhkj.yymall.bean.db.UserConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recnetSearchBeanDaoConfig;
    private final DaoConfig userConfigDaoConfig;

    private final RecnetSearchBeanDao recnetSearchBeanDao;
    private final UserConfigDao userConfigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recnetSearchBeanDaoConfig = daoConfigMap.get(RecnetSearchBeanDao.class).clone();
        recnetSearchBeanDaoConfig.initIdentityScope(type);

        userConfigDaoConfig = daoConfigMap.get(UserConfigDao.class).clone();
        userConfigDaoConfig.initIdentityScope(type);

        recnetSearchBeanDao = new RecnetSearchBeanDao(recnetSearchBeanDaoConfig, this);
        userConfigDao = new UserConfigDao(userConfigDaoConfig, this);

        registerDao(RecnetSearchBean.class, recnetSearchBeanDao);
        registerDao(UserConfig.class, userConfigDao);
    }
    
    public void clear() {
        recnetSearchBeanDaoConfig.clearIdentityScope();
        userConfigDaoConfig.clearIdentityScope();
    }

    public RecnetSearchBeanDao getRecnetSearchBeanDao() {
        return recnetSearchBeanDao;
    }

    public UserConfigDao getUserConfigDao() {
        return userConfigDao;
    }

}
